export const LocalImages = {
  leftIcon: require('../assets/images/arrow.png'),
  womenIcon: require('../assets/images/womanicon.png'),
  likeIcon: require('../assets/images/like.png'),
  dislikeIcon: require('../assets/images/dislike.png'),
  shareIcon: require('../assets/images/share.png'),
  heartIcon: require('../assets/images/heart.png'),
  moneyIcon: require('../assets/images/money.png'),
  playIcon: require('../assets/images/play.png'),
  decrTime: require('../assets/images/dectime.png'),
  incrTime: require('../assets/images/inctime.png'),
  fullScreen: require('../assets/images/fullscreen.png'),
  doticon: require('../assets/images/dots.png'),
  pauseIcon: require('../assets/images/pause.png'),
  expandIcon: require('../assets/images/expand.png'),
};
